meshes:
  segments:
    - 14
    - 17
    - 20
    - 25
    - 33
    - 50
    - 100
  random_factors:
    - 0.005
    - 0.01
    - 0.015
    - 0.02
    - 0.025
    - 0.03
    - 0.035
    - 0.04

function: sin
type: integral