mesh_file: "./input/mesh.mesh"
density_file: "./input/density.gf"
temperature_file: "./input/temperature.gf"
ionization_file: "./input/ionization.gf"
lasers:
  - wavelength: 1315e-7
    direction:
      x: -1
      y: 0.577350 #30 deg
    spatial_FWHM: 20e-4
    energy: 1
    start_point:
      x: 140e-4
      y: -50e-4
    end_point:
      x: 140e-4
      y: -10e-4
    rays_count: 1001
    estimate_bremsstrahlung: true
    estimate_resonance: true
    estimate_gain: false
    gradient_type: "h1"