mesh_file: "./input/mesh.mesh"
ion_dens_file: "./input/density.gf"
atomic_mass: 55.845
temperature_file: "./input/temperature.gf"
ionization_file: "./input/ionization.gf"
rays_filename: "./output/rays.msgpack"
absorbed_energy_filename: "./output/absorbed_energy.gf"
lasers:
  - wavelength: 25.5e-7
    direction:
      x: -0.005 # 5 mrad
      y: 1
    spatial_FWHM: 10e-4
    energy: 1
    start_point:
      x: 10e-4
      y: -1e-4
    end_point:
      x: 50e-4
      y: -1e-4
    rays_count: 1001
    energy_exchange:
      - "gain"
    grad_type: "ls"
    gain_file: "./input/gain.gf"
