mesh_file: "./input/mesh.vtk"
ion_dens_file: "./input/density.gf"
atomic_mass: 55.845
temperature_file: "./input/temperature.gf"
ionization_file: "./input/ionization.gf"
rays_filename: "output/rays.msgpack"
absorbed_power_filename: "output/power.gf"
mesh_output_filename: "output/mesh.mfem"
lasers:
  - wavelength: 25.5e-7
    direction:
      x: -0.005
      y: 1
    power: 1
    spatial_FWHM: 70e-4
    start_point:
      x: 2e-4
      y: -0.03
    end_point:
      x: 105e-4
      y: -0.03
    rays_count: 1000
    power_exchange: ["gain"]
    gain_file: "./input/gain.gf"
    grad_type: "ls"